name: Sync Algorithm List

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download JSON file
        run: |
          # Create the folder matching your URL path
          mkdir -p supplemental-ui/softbinding-alg-list
          
          # Download and save with the EXACT filename you want in the URL
          curl -s https://raw.githubusercontent.com/c2pa-org/softbinding-algorithm-list/refs/heads/main/softbinding-algorithm-list.json -o supplemental-ui/softbinding-alg-list/softbinding-algorithm-list.json

      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add supplemental-ui/softbinding-alg-list/softbinding-algorithm-list.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update softbinding algorithm list to latest" && git push)
