name: Sync Softbinding Algorithm List

on:
  schedule:
    # This runs at 00:00 UTC every day. 
    - cron: '0 0 * * *'
  workflow_dispatch: # Allows you to run it manually for testing

jobs:
  update-json:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download JSON file
        run: |
          mkdir -p softbinding-alg-list 
          curl -s https://raw.githubusercontent.com/c2pa-org/softbinding-algorithm-list/refs/heads/main/softbinding-algorithm-list.json -o softbinding-alg-list/softbinding-algorithm-list.json

      - name: Commit and push if changed
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add softbinding-alg-list/softbinding-algorithm-list.json
          if git diff --cached --quiet; then
            echo "No changes detected"
          else
            git commit -m "chore: update softbinding-algorithm-list.json"
            git push
          fi
